### ISSUE TITLE
confusing $Nullable in metadata

### ISSUE THREAD

**Issue by guai** [exxcellent/olingo-jpa-processor-v4#40]
in JPA there are `@JoinColumn(nullable)` and `@ManyToOne(optional)`.
It seems `@ManyToOne(optional)` goes to `$Nullable` in metadata instead of `@JoinColumn(nullable)`.

They are not the same. `nullable` means the column in the DB is nullable, and `optional` is for some other runtime usage.

With eclipselink and a field annotated with
```
	@JoinColumn(nullable = false)
	@ManyToOne
```
I got no `$Nullable` in metadata (which is `true` by default).

**Comment by rzozmann** [comment]
The OData-JPA-Adapter is neither using @ManyToOne (or @OnoeToOne) nor @JoinColumn to determine the _nullable_ flag for relationships. As you can see in class IntermediateNavigationProperty#lazyBuildEdmItem() the _nullable_ flag depends only on the optional value of JPA attribute configuration (SingularAttribute#isOptional()). So **JPA** will decide whether the relationship becomes _nullable_.
And JPA means, that it depends from the used JPA provider (implementation) and may differ between EclipseLink, Hibernate,...
